deploy and test files added
Shivansh070707/Tasks pull request #5
Opened 2023-01-13 17:18 UTC by Shivansh070707

2023-01-15 20:24 UTC, sumit03guha requested changes
### Test cases
- Add more test cases to assert the storage variables using the `StratX2Getter` contract.
- Rename the `StratX2Getter.Facet` to `StratX2GetterFacet`.

### Contracts
- It is better to append the term `Facet` after every facet contract.
- It is better to create interfaces separately in the `interfaces` folder. https://github.com/Shivansh070707/Tasks/blob/cc465b63d82604805c56fb427b791db2244dddce/Task4/contracts/diamond/facets/StratX2Facet.sol#L11
- Use functions instead of modifiers. It helps in saving gas. https://github.com/Shivansh070707/Tasks/blob/cc465b63d82604805c56fb427b791db2244dddce/Task4/contracts/diamond/facets/StratX2Facet.sol#L19
- Remove the  console logs after testing. https://github.com/Shivansh070707/Tasks/blob/cc465b63d82604805c56fb427b791db2244dddce/Task4/contracts/diamond/facets/StratX2Facet.sol#L9
- Instead of making the `StratX2Facet` as pausable, create a Pausable storage struct in the diamond and use it in the facets.
- Use different revert strings within the same function. https://github.com/Shivansh070707/Tasks/blob/cc465b63d82604805c56fb427b791db2244dddce/Task4/contracts/diamond/facets/StratX2Facet.sol#L324 https://github.com/Shivansh070707/Tasks/blob/cc465b63d82604805c56fb427b791db2244dddce/Task4/contracts/diamond/facets/StratX2Facet.sol#L325

### Deployment
- Add functionality to save the addresses and ABIs of the deployments.

2023-01-17 20:18 UTC, sumit03guha requested changes
1. Use better filenames instead of `index.ts`. Example : `facet.test.ts`
2. Remove unnecessary white spaces.

2023-01-17 20:18 UTC, sumit03guha commented on Task4/scripts/deploy.ts
>        '0xbb4cdb9cbd36b01bd1cbaebf2de08d9173bc095c',
use descriptive names for the addresses by declaring a named variable

2023-01-17 20:18 UTC, sumit03guha commented on Task4/scripts/deploy.ts
>        '0x7a250d5630B4cF539739dF2C5dAcb4c659F2488D',
use descriptive names for the addresses by declaring a named variable

2023-01-17 20:18 UTC, sumit03guha commented on Task4/scripts/deploy.ts
> +
remove white spaces

2023-01-17 20:18 UTC, sumit03guha commented on Task4/contracts/diamond/libraries/LibDiamond.sol
> +        uint8 lock; // this vault is purely for staking. eg. WBNB-AUTO staking vault.
if `lock` is not used anywhere, remove it

2023-01-17 20:18 UTC, sumit03guha commented on Task4/scripts/deploy.ts
> +    JSON.stringify(diamondCutFacetData, null, '\t')
instead of `\t` use `2` indentation while saving JSON

2023-01-17 20:18 UTC, sumit03guha commented on Task4/hardhat.config.ts
> +    runOnCompile: true,
better to keep the `runOnCompile` as `false`.

2023-01-19 10:12 UTC, Shivansh070707 commented on Task4/scripts/deploy.ts
>        '0xbb4cdb9cbd36b01bd1cbaebf2de08d9173bc095c',
already up

2023-01-19 10:18 UTC, merged